name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build binary
        run: |
          make build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/extract_bitwarden_totp
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
