name: Nightly Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '>=1.17.0'

    - name: Build for multiple architectures
      run: |
        GOOS=linux GOARCH=amd64 go build -o extract_bitwarden_totp_linux_amd64
        GOOS=linux GOARCH=arm64 go build -o extract_bitwarden_totp_linux_arm64
        GOOS=darwin GOARCH=amd64 go build -o extract_bitwarden_totp_darwin_amd64

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          extract_bitwarden_totp_linux_amd64
          extract_bitwarden_totp_linux_arm64
          extract_bitwarden_totp_darwin_amd64
        github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        release_name: Nightly Build - ${{ env.GITHUB_SHA }}
