name: Nightly

on:
  push:
    branches:
      - main

env:
  TAG_NAME: nightly-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: latest

    - name: Build for amd64
      run: |
        GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/extract_bitwarden_totp-linux-amd64 cmd/cli/cli.go

    - name: Build for arm64
      run: |
        GOARCH=arm64 GOOS=linux go build -ldflags="-s -w" -o bin/extract_bitwarden_totp-linux-arm64 cmd/cli/cli.go

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/extract_bitwarden_totp-linux-amd64,bin/extract_bitwarden_totp-linux-arm64
        github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        release_name: v${{ env.TAG_NAME }}
        draft: false
        prerelease: true
