name: Nightly Build and Release

on:
  push:
    branches:
      - main

env:
  GO111MODULE: on
  GO_VERSION: ">=1.17.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build for macOS
      run: |
        GOOS=darwin GOARCH=amd64 go build -o bin/extract_bitwarden_totp-darwin-amd64

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o bin/extract_bitwarden_totp-linux-amd64

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o bin/extract_bitwarden_totp-windows-amd64.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        tag_name: nightly-${{ env.GITHUB_SHA }}
        release_name: Nightly Build ${{ env.GITHUB_SHA }}
        files: bin/extract_bitwarden_totp-darwin-amd64,bin/extract_bitwarden_totp-linux-amd64,bin/extract_bitwarden_totp-windows-amd64.exe
