name: Nightly Build and Release

on:
  push:
    branches:
      - main

env:
  TAG_NAME: "nightly-${{ env.GITHUB_SHA }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: latest
      - name: Build for amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o extract_bitwarden_totp_linux_amd64 .
      - name: Build for arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -o extract_bitwarden_totp_linux_arm64 .
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        with:
          name: v${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          assets: |
            extract_bitwarden_totp_linux_amd64
            extract_bitwarden_totp_linux_arm64
